name: Bug Report
description: Report a bug
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Tell us how to reproduce it
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior

  - type: input
    id: device
    attributes:
      label: Device / Browser
