name: Feature Request
description: Suggest a new feature
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: Your idea
    validations:
      required: true
